apiVersion: flowfunc.dev/v1beta1
kind: Pipeline
metadata:
  name: character-roster-builder
spec:
  default_module: examples.zip.character_builder

  params:
    character_names:
      value: ["Astra", "Gideon", "Seraphina", "Kael"]
    character_archetypes:
      value: ["Mage", "Warrior", "Healer", "Rogue"]
    power_levels:
      value: [85, 92, 78, 95]
    creation_years:
      value: [2021, 2019, 2022, 2020]

  steps:
    - name: "create_character_profile"
      description: "Builds a structured profile for each character by zipping four lists."
      options:
        map_mode: zip
      params:
        name: "{{ globals.character_names }}"
        archetype: "{{ globals.character_archetypes }}"
        power_level: "{{ globals.power_levels }}"
        design_year: "{{ globals.creation_years }}"
      produces: "character_roster"

  artifacts:
    "final_roster.json": "{{ steps.create_character_profile.produces.character_roster }}"