[project]
name = "nl-text-summarization"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
example = [
    "numpy>=2.2.6",
    "pipefunc[all]>=0.76.0",
    "nltk==3.9.1"
]
