apiVersion: flowfunc.dev/v1beta1
kind: Pipeline
metadata:
  name: multi-target-health-check
spec:
  default_module: examples.broadcast.health_checker

  params:
    environments:
      value: ["playground", "staging", "production"]
    regions:
      value: ["us-east-1", "eu-west-1", "ap-southeast-2"]

  steps:
    - name: "check_service_health"
      description: "Checks service health across all environments and regions."
      options:
        map_mode: broadcast
      params:
        environment: "{{ params.environments }}"
        region: "{{ params.regions }}"
      produces: "health_status_grid"

  artifacts:
    "health_check_summary.json": "{{ steps.check_service_health.produces.health_status_grid }}"