apiVersion: flowfunc.dev/v1beta1
kind: Pipeline
metadata:
  name: pokeapi-analysis-pipeline
  version: "1.0.0"
  description: "A pipeline to fetch, process, and summarize data from the PokéAPI."
spec:
  default_module: examples.pokemon_analysis.main

  inputs:
    pokemon_ids:
      description: "A list of Pokémon IDs to fetch."
      type: "list"
      value: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

  steps:
    - name: "fetch_pokemon_data"
      description: "Fetches raw data for each Pokémon ID in parallel."
      inputs:
        pokemon_id: "{{ globals.pokemon_ids }}"
      outputs: "pokemon_data"

    - name: "extract_basic_stats"
      description: "Extracts key stats from the raw data for each Pokémon."
      inputs:
        pokemon_data: "{{ steps.fetch_pokemon_data.outputs.pokemon_data }}"
      outputs: "all_stats"

    - name: "summarize_pokemon_stats"
      description: "Aggregates the individual stats into a single summary."
      inputs:
        all_stats: "{{ steps.extract_basic_stats.outputs.all_stats }}"
      outputs: "final_summary"
      options:
        map_mode: "none"

  artifacts:
    final_summary: "pokemon_summary.json"